// AUTO-GENERATED by convert_assets.py -- DO NOT EDIT MANUALLY
// Single include for all converted app bitmap assets.
// Usage in any applet:  #include "all_assets.h"

#ifndef GENERATED_ALL_ASSETS_H
#define GENERATED_ALL_ASSETS_H

#include "FlappyBirdApplet_char.h"
#include "FlappyBirdApplet_end.h"
#include "FlappyBirdApplet_start.h"
#include "bootscreen.h"

#endif // GENERATED_ALL_ASSETS_H
