// AUTO-GENERATED by convert_assets.py -- DO NOT EDIT MANUALLY
// Source: FlappyBirdApplet_char.png  (10x8 px)
//
// Usage:
//   display.drawBitmap(x, y, FlappyBirdApplet_char_bmp, FLAPPYBIRDAPPLET_CHAR_WIDTH, FLAPPYBIRDAPPLET_CHAR_HEIGHT, SSD1306_WHITE);

#ifndef GENERATED_FLAPPYBIRDAPPLET_CHAR_H
#define GENERATED_FLAPPYBIRDAPPLET_CHAR_H

#include <Arduino.h>

#define FLAPPYBIRDAPPLET_CHAR_WIDTH  10
#define FLAPPYBIRDAPPLET_CHAR_HEIGHT  8

// Adafruit GFX monochrome bitmap (MSB-first, 1 = OLED pixel ON)
const uint8_t FlappyBirdApplet_char_bmp[] PROGMEM = {
  0x00, 0x00, 0x3F, 0x00, 0x75, 0x80, 0x54, 0x80, 0x77, 0xC0, 0x67, 0xC0, 0x3F, 0x80, 0x00, 0x00
};

#endif // GENERATED_FLAPPYBIRDAPPLET_CHAR_H
